---

dist: xenial
language: python
python: 3.8.3
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - black --check .
  - pytest
  - pytest --cov=code_fmt --cov-fail-under=100
after_success:
  - coveralls
env:
  - PYTHONBREAKPOINT=0
